<DIV align="center" style="font-size : 10pt;">
<A href="http://www.88ag.com/link/" 
  target=_blank>友情链接</A> | <A href="http://www.88ag.com/page/aboutus.html" 
  target=_blank>关于我们</A> | <A href="http://www.88ag.com/page/contactus.html" 
  target=_blank>联系我们</A> | <A href="http://www.88ag.com/page/ads.html" 
  target=_blank>广告服务</A>
<HR width="780" color="#cccccc" size="1">
版权所有 温岭淘园(<A href="http://www.88ag.com">
http://www.88ag.com</A>) 联系QQ:706168 电话:0576-8634563<BR>
地址：浙江省温岭市太平街道文化路222号 <BR>
<A href="http://www.miibeian.gov.cn" target=_blank>浙ICP备05000333号 </A>
<span style="display:none"><script language="javascript" type="text/javascript" src="http://js.users.51.la/1103894.js"></script></span>
</DIV>