<table width="980" align="center" cellspacing="1" bgcolor="#b9b9ff" cellpadding="0" cellspacing="0">
<tr>
<td width="205" height="65" align="center"bgcolor="#ffffff"><a href="http://www.88ag.com"><img src="logo.gif"></a></td>
<td width="665" align="center" bgcolor="#ffffff" style="font-size : 10pt;letter-spacing : 1pt;line-height : 17pt;">
<a href="http://www.88ag.com">首页</a> | 
 <a href="http://vod.88ag.com" target=_blank">免费电影</a> | 
      <a href="http://flash.88ag.com" target=_blank">动漫</a> | 
      <a href="http://www.88ag.com/picture" target=_blank">美图</a> | 
      <a href="http://down.88ag.com" target=_blank">下载</a> | 
      <a href="http://www.88ag.com/tv" target=_blank">直播</a> | 
      <a href="http://www.88ag.com/sex" target=_blank">两性</a> | 
      <a href="http://www.88ag.com/v" target=_blank" target=_blank">视频</a> | 
      <a href="http://www.88ag.com/zhuan" target=_blank">网赚</a> | 
      <a href="http://www.88ag.com/house" target=_blank">房产</a> | 
      <a href="http://www.88ag.com/article" target=_blank">资讯</a> | 
      <a href="http://bbs.88ag.com" target=_blank">论坛</a> | <BR>
      <a href="http://shop.88ag.com" target=_blank">商城</a> | 
      <a href="http://www.88ag.com/info" target=_blank">生活分类</a> | 
      <a href="http://www.88ag.com/yp/buy.php" target=_blank">供求</a> | 
      <a href="http://www.88ag.com/yp/job.php" target=_blank">人才</a> | 
      <a href="http://www.88ag.com/house/listinfo.php?infocat=1" target=_blank">租房</a> | 
      <a href="http://www.88ag.com/house/listinfo.php?infocat=4" target=_blank">售房</a> | 
      <a href="http://www.88ag.com/info/list.php?catid-24.html" target=_blank">外卖</a> | 
      <a href="http://www.88ag.com/info/list.php?catid-19.html" target=_blank">家政</a> | 
      <a href="http://www.88ag.com/info/list.php?catid-21.html" target=_blank">促销</a> | 
      <a href="http://www.88ag.com/yp" target=_blank">黄页</a> | 
      <a href="http://www.88ag.com/wenba" target=_blank">问吧</a> | 
      <a href="http://www.wlidc.com" target=_blank">域名</a> | </td>
<td align="center"bgcolor="#ffffff">
<A href="http://vod.88ag.com" target="_blank" style="color : red;">电影一站</A><BR><BR>
<A href="http://vod.vodwl.cn" target="_blank"style="color : red;">电影二站</A>
</td>
       </tr>
</tr>
</table></center>
